In [ ]:
from docx import Document
import os
from PIL import Image
from io import BytesIO

def extract_docx_content(file_path):
    # Открываем документ
    doc = Document(file_path)
    
    # Извлекаем текст
    text = []
    for paragraph in doc.paragraphs:
        ttt = paragraph.text
        text.append(paragraph.text)
    
    # Извлекаем таблицы
    tables = []
    for table in doc.tables:
        table_data = []
        for row in table.rows:
            row_data = [cell.text for cell in row.cells]
            table_data.append(row_data)
        tables.append(table_data)
    
    # Извлекаем изображения
    images = []
    rels = doc.part.rels
    for rel in rels.values():
        if "image" in rel.target_ref:
            img_data = rel.target_part.blob
            images.append(Image.open(BytesIO(img_data)))
    
    return text, tables, images



# Пример использования
docx_file = "DOC/pdf_urez59_0.docx"
docx_file = "DOC/pdf_urez1_500.docx"
docx_file = "DOC/pdf_urez500_1000.docx"
docx_file = "DOC/pdf_urez1000_1496.docx"
docx_file = "DOC/ASME Sec II-D-Metric.docx"

text, tables, images = extract_docx_content(docx_file)

# Печать текста
#print("Текст документа:")
#print("\n".join(text))

# Печать таблиц
filename = 'Tab.txt'
file = open(filename, 'w')

for i, table in enumerate(tables):
    print(f"Таблица {i+1}:", file = file)
    for row in table:
#        print(row[1:], file = file)
        print(row, file = file)
file.close()

print('End Program')
# Сохранение изображений
#output_dir = "extracted_images"
#os.makedirs(output_dir, exist_ok=True)
#for i, img in enumerate(images):
#    img.save(os.path.join(output_dir, f"image_{i+1}.png"))
#    print(f"Сохранено изображение: image_{i+1}.png")

In [ ]:
import pandas as pd

filename = "DOC/ASME Sec II-D-Metric.docx"
# Открытие файла и обработка строк
with open(filename, 'r', encoding='utf-8') as file:
    try:
        lines = file.readlines()
    except:
        lines = '111111111111111111111111111111'

# Поиск строки с "Таблица 18" и определение её номера
for i, line in enumerate(lines):
    if 'Таблица 18:' in line:
        header_index = i + 1  # Следующая строка
        break

# Преобразование следующей строки в заголовок
header = lines[header_index].strip().split()  # Разделение строки по пробелам, измените, если другой разделитель

# Извлечение 45 строк данных
data = [line.strip().split() for line in lines[header_index + 1:header_index + 46]]

# Создание DataFrame
df = pd.DataFrame(data, columns=header)

# Вывод результата
print(df)

# Сохранение DataFrame в файл (если нужно)
df.to_csv('output.csv', index=False, encoding='utf-8')

In [ ]:
import pandas as pd

filename = "DOC/ASME Sec II-D-Metric.docx"
# Открытие файла и обработка строк
with open(filename, 'r', encoding='cp1251') as file:  # Изменено на 'cp1251'
    lines = file.readlines()

# Поиск строки с "Таблица 18" и определение её номера
for i, line in enumerate(lines):
    if 'Таблица 18' in line:
        header_index = i + 1  # Следующая строка
        break

# Преобразование следующей строки в заголовок
header = lines[header_index].strip().split()  # Разделение строки по пробелам, измените, если другой разделитель

# Извлечение 45 строк данных
data = [line.strip().split() for line in lines[header_index + 1:header_index + 46]]

# Создание DataFrame
df = pd.DataFrame(data, columns=header)

# Вывод результата
print(df)

# Сохранение DataFrame в файл (если нужно)
df.to_csv('output.csv', index=False, encoding='utf-8')

In [ ]:

# Преобразование следующей строки в заголовок
header = lines[header_index].strip().split()  # Разделение строки по пробелам, измените, если другой разделитель

# Извлечение 45 строк данных
data = [line.strip().split() for line in lines[header_index + 1:header_index + 46]]

# Создание DataFrame
df = pd.DataFrame(data, columns=header)

# Вывод результата
print(df)

# Сохранение DataFrame в файл (если нужно)
df.to_csv('output.csv', index=False, encoding='utf-8')

In [ ]:
from docx import Document
from PIL import Image
from io import BytesIO

def extract_docx_content(file_path, start, end):
    # Открываем документ
    doc = Document(file_path)
    
    # Извлекаем текст только из заданного диапазона строк
    text = []
    for i, paragraph in enumerate(doc.paragraphs):
        if start <= i + 1 <= end:  # Учитываем нумерацию с 1
            ttt = paragraph.text
            text.append(paragraph.text)
    print('text = ', text)
    
    # Извлекаем таблицы (включить всю таблицу, если она попадает в диапазон)
    tables = []
    for table in doc.tables:
        table_data = []
        for row in table.rows:
            row_data = [cell.text for cell in row.cells]
            table_data.append(row_data)
        tables.append(table_data)
    
    # Извлекаем изображения
    images = []
    rels = doc.part.rels
    for rel in rels.values():
        if "image" in rel.target_ref:
            img_data = rel.target_part.blob
            images.append(Image.open(BytesIO(img_data)))
    
    return text, tables, images

# Пример использования
docx_file = "DOC/doc_urez59_0.docx"
start_line = 1  # Начальная строка
end_line = 2    # Конечная строка
text, tables, images = extract_docx_content(docx_file, start_line, end_line)

# Вывод извлечённого текста
print("Извлечённый текст:")
print("\n".join(text))

In [ ]:
from docx import Document
from PIL import Image
from io import BytesIO

def extract_docx_content(file_path, start, end):
    # Открываем документ
    doc = Document(file_path)
    
    # Извлекаем текст только из заданного диапазона строк
    text = []
    for i, paragraph in enumerate(doc.paragraphs):
        if start <= i + 1 <= end:  # Учитываем нумерацию с 1
            if paragraph.text.strip():  # Проверяем, что текст не пустой
                text.append(paragraph.text.strip())  # Убираем пробелы
    
    # Печать текста для отладки
    print('text = ', text)
    
    # Извлекаем таблицы (включить всю таблицу, если она попадает в диапазон)
    tables = []
    for table in doc.tables:
        table_data = []
        for row in table.rows:
            row_data = [cell.text for cell in row.cells]
            table_data.append(row_data)
        tables.append(table_data)
    
    # Извлекаем изображения
    images = []
    rels = doc.part.rels
    for rel in rels.values():
        if "image" in rel.target_ref:
            img_data = rel.target_part.blob
            images.append(Image.open(BytesIO(img_data)))
    
    return text, tables, images

# Пример использования
docx_file = "DOC/pdf_urez59_0.docx"
start_line = 10  # Начальная строка
end_line = 20    # Конечная строка
text, tables, images = extract_docx_content(docx_file, start_line, end_line)

# Вывод извлечённого текста
print("Извлечённый текст:")
print("\n".join(text))

In [ ]:
list_i =  [5493, 5725, 5960, 6192, 6420, 6648, 6876, 7104, 7332, 7560, 7788, 8016, 8244, 
           8472, 8700, 8929, 9174, 9419, 9648, 9876, 10105, 10335, 10564, 10792, 11020, 
           11248, 11476, 11709, 11942, 12170, 12399, 12628, 12856, 13084, 13312, 13543, 
           13774, 13949]
len0 = 38

for i in range(37):
    a1 = list_i[i+1]
    a0 = list_i[i]
    d = a1 - a0
    print(d)

In [ ]:
from docx import Document

def get_line_from_word(file_path, line_number):
    """
    Читает строку с заданным номером из документа Word.
    :param file_path: Путь к файлу Word (.docx)
    :param line_number: Номер строки (начиная с 1)
    :return: Текст строки или сообщение об ошибке
    """
    try:
        doc = Document(file_path)
        lines = []
        # Собираем текст из всех абзацев
        for paragraph in doc.paragraphs:
            lines.extend(paragraph.text.splitlines())
        
        # Проверяем, существует ли строка с заданным номером
        if 0 < line_number <= len(lines):
            return lines[line_number - 1]
        else:
            return f"Строки с номером {line_number} нет в документе."
    except Exception as e:
        return f"Ошибка при чтении файла: {e}"

# Пример использования

docx_file = "DOC/pdf_urez59_0.docx"
#docx_file = "DOC/pdf_urez1_500.docx"
#docx_file = "DOC/pdf_urez500_1000.docx"
#docx_file = "DOC/pdf_urez1000_1496.docx"
#docx_file = "DOC/ASME Sec II-D-Metric.docx"

file_path = docx_file  # Укажите путь к файлу

for line_number in range(20):  # Номер строки, которую нужно прочитать
    result = get_line_from_word(file_path, line_number)
    print(result)

In [1]:
#################  main ###################
import ast
import pandas as pd

def read_lines_from_file(filename, start, end):
    try:
        with open(filename, 'r', encoding='utf-8') as file:
            lines = file.readlines()
            return lines[start-1:end]  # Номера строк приводятся к индексации с 0
    except FileNotFoundError:
        print(f"Файл {filename} не найден.")
        return []
    except IndexError:
        print("Некорректные значения start или end.")
        return []


def find_line_with_text(filename, search_text):
    try:
        with open(filename, 'r', encoding='utf-8') as file:
            for i, line in enumerate(file, start=1):  # Нумерация строк с 1
                if search_text in line:
                    return i
        return None  # Если текст не найден
    except FileNotFoundError:
        print(f"Файл {filename} не найден.")
        return None

def stroka_v_spisok(input_str):
    # Преобразование строки в список
    try:
        result_list = ast.literal_eval(input_str)
    #    print(result_list)
    except (ValueError, SyntaxError):
        print("Ошибка: Некорректный формат строки.")
    return result_list

def convert_value(value):
    if value == None:
        return None
    try:
        return int(value)  # Сначала пытаемся преобразовать в int
    except ValueError:
        try:
            return float(value)  # Если не удалось, пытаемся преобразовать в float
        except ValueError:
            return value  # Если не удалось, возвращаем значение как есть

def dob_sprava(df1, df2):
    return pd.concat([df1, df2], axis=1)

def dob_snizu(df1, df2):
    return pd.concat([df1, df2], axis=0, ignore_index=True)

def ubrat_kol(df, list_col):
    return df.drop(df.columns[list_col], axis=1)



DF = {}
filename = 'Tab.txt'

for no in range(18, 22):   #22):
    no_tab = ' ' + str(no)
    search_text = "Таблица" + str(no_tab) + ":"

    No = find_line_with_text(filename, search_text)
    No_header = No + 1

    start = No_header  # Начальная строка (включительно)
    end = No_header + 45   # Конечная строка (включительно)

    Spisok = []
    lines = read_lines_from_file(filename, start, end)
    for line in lines:
        spisok = stroka_v_spisok(line)
        Spisok.append(spisok)

    df = pd.DataFrame(Spisok[1:], columns=Spisok[0])
    #df = df.applymap(convert_value)
    df = df.map(convert_value)

    DF[no] = df

df18 = ubrat_kol(DF[18], [1])
df19 = ubrat_kol(DF[19], [0])
df1819 = dob_sprava(df18, df19)

df20 = ubrat_kol(DF[20], [0])
df21 = ubrat_kol(DF[21], [0])
df2021 = dob_sprava(df20, df21)

dffin = dob_sprava(df1819, df2021)



L = list(dffin.columns)
d = {i : L[i] for i in range(len(L))}
dffin.columns = range(len(dffin.columns))
dffin.to_csv("dffin.csv", index=False)  #, header=False)

mask = (dffin[10] > 310) & (dffin[10] < 330)
dffilter = dffin[mask]
dffilter.to_csv('filter.csv')

In [29]:
#################  main ###################
import ast
import pandas as pd

def read_lines_from_file(filename, start, end):
    try:
        with open(filename, 'r', encoding='utf-8') as file:
            lines = file.readlines()
            return lines[start-1:end]  # Номера строк приводятся к индексации с 0
    except FileNotFoundError:
        print(f"Файл {filename} не найден.")
        return []
    except IndexError:
        print("Некорректные значения start или end.")
        return []


def find_line_with_text(filename, search_text):
    try:
        with open(filename, 'r', encoding='utf-8') as file:
            for i, line in enumerate(file, start=1):  # Нумерация строк с 1
                if search_text in line:
                    return i
        return None  # Если текст не найден
    except FileNotFoundError:
        print(f"Файл {filename} не найден.")
        return None

def stroka_v_spisok(input_str):
    # Преобразование строки в список
    try:
        result_list = ast.literal_eval(input_str)
    #    print(result_list)
    except (ValueError, SyntaxError):
        print("Ошибка: Некорректный формат строки.")
    return result_list

def convert_value(value):
    if value == None:
        return None
    try:
        return int(value)  # Сначала пытаемся преобразовать в int
    except ValueError:
        try:
            return float(value)  # Если не удалось, пытаемся преобразовать в float
        except ValueError:
            return value  # Если не удалось, возвращаем значение как есть

def dob_sprava(df1, df2):
    return pd.concat([df1, df2], axis=1)

def dob_snizu(df1, df2):
    return pd.concat([df1, df2], axis=0, ignore_index=True)

def ubrat_kol(df, list_col):
    return df.drop(df.columns[list_col], axis=1)



DF = {}
filename = 'Tab.txt'
n = 5
no1 = 18 + 4*n
no2 = 22 + 4*n
for no in range(no1, no2):
    no_tab = ' ' + str(no)
    search_text = "Таблица" + str(no_tab) + ":"

    No = find_line_with_text(filename, search_text)
    No_header = No + 1

    start = No_header  # Начальная строка (включительно)
    end = No_header + 45   # Конечная строка (включительно)

    Spisok = []
    lines = read_lines_from_file(filename, start, end)
    for line in lines:
        spisok = stroka_v_spisok(line)
        Spisok.append(spisok)

    df = pd.DataFrame(Spisok[1:], columns=Spisok[0])
    df = df.map(convert_value)

    DF[no] = df

df18 = ubrat_kol(DF[no1], [1])
df19 = ubrat_kol(DF[no1 + 1], [0])
df1819 = dob_sprava(df18, df19)

df20 = ubrat_kol(DF[no1 + 2], [0])
df21 = ubrat_kol(DF[no1 + 3], [0])
df2021 = dob_sprava(df20, df21)

dffin = dob_sprava(df1819, df2021)



L = list(dffin.columns)
d = {i : L[i] for i in range(len(L))}
Lfin = len(dffin.columns)
dffin.columns = range(Lfin)
filename = 'dffin' + str(n) + '.csv'
dffin.to_csv(filename, index=False)

filename = 'dictionary' + str(n) + '.txt'
f = open(filename, 'w')
print('Lfin = ', Lfin, file = f)
for i in range(len(d)):
    f.write('\n')
    print('i = ', i, '-------------------', file = f)
    f.write(d[i])
f.close()

In [33]:
dffin[10]

0     275.0
1     275.0
2     275.0
3     290.0
4     290.0
5     310.0
6     310.0
7     310.0
8     345.0
9     380.0
10    380.0
11    380.0
12    415.0
13    415.0
14    410.0
15    310.0
16    325.0
17    345.0
18    380.0
19    415.0
20    415.0
21    415.0
22    415.0
23    415.0
24    415.0
25    450.0
26    345.0
27    345.0
28    415.0
29    380.0
30    485.0
31    485.0
32    515.0
33    345.0
34      NaN
35      NaN
36    330.0
37    340.0
38    360.0
39    370.0
40    415.0
41    345.0
42    345.0
43    414.0
44    414.0
Name: 10, dtype: float64

In [34]:
mask = (dffin[10] > 310)
dffilter = dffin[mask]
filename = 'filter' + str(n) + '.csv'
dffilter.to_csv(filename)

In [35]:
dffilter

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
8,9,Plate,SA–537,None,K12437,3,65 < t ≤ 100,1,3.0,515,...,None,None,None,None,None,None,None,None,None,None
9,10,Plate,SA–537,None,K12437,2,65 < t ≤ 100,1,3.0,515,...,None,None,None,None,None,None,None,None,None,None
10,11,Wld. pipe,SA–691,CMSH–80,K12437,None,65 < t ≤ 100,1,3.0,515,...,None,None,None,None,None,None,None,None,None,None
11,12,Plate,SA–738,C,K02008,None,65 < t ≤ 100,1,3.0,515,...,None,None,None,None,None,None,None,None,None,None
12,13,"Plate, sheet, bar",SA–572,60,None,None,t ≤ 32,None,NaN,520,...,None,None,None,None,None,None,None,None,None,None
13,14,Round bar,SA–572,60,None,None,t ≤ 90,None,NaN,520,...,None,None,None,None,None,None,None,None,None,None
14,15,"Sheet, strip",SA–1011,60,HSLAS,1,None,None,NaN,520,...,None,None,None,None,None,None,None,None,None,None
16,17,Plate,SA–299,B,K02803,None,≤25,1,3.0,550,...,None,None,None,None,None,None,None,None,None,None
17,18,Forgings,SA–765,IV,K02009,None,None,1,3.0,550,...,None,None,None,None,None,None,None,None,None,None
18,19,Plate,SA–537,None,K12437,3,≤65,1,3.0,550,...,None,None,None,None,None,None,None,None,None,None
19,20,Plate,SA–537,None,K12437,2,≤65,1,3.0,550,...,None,None,None,None,None,None,None,None,None,None
20,21,Wld. pipe,SA–671,CD80,K12437,None,≤65,1,3.0,550,...,None,None,None,None,None,None,None,None,None,None
21,22,Wld. pipe,SA–672,D80,K12437,None,≤65,1,3.0,550,...,None,None,None,None,None,None,None,None,None,None
22,23,Wld. pipe,SA–691,CMSH–80,K12437,None,≤65,1,3.0,550,...,None,None,None,None,None,None,None,None,None,None
23,24,Plate,SA–738,C,K02008,None,≤65,1,3.0,550,...,None,None,None,None,None,None,None,None,None,None
24,25,Plate,SA–841,B,None,2,≤65,1,3.0,550,...,None,None,None,None,None,None,None,None,None,None
25,26,"Plate, sheet, bar",SA–572,65,None,None,t ≤ 32,None,NaN,550,...,None,None,None,None,None,None,None,None,None,None
26,27,Plate,SA–612,None,K02900,None,12.5 < t ≤ 25,10C,1.0,560,...,None,None,None,None,None,None,None,None,None,None
27,28,Plate,SA–612,None,K02900,None,≤12.5,10C,1.0,570,...,None,None,None,None,None,None,None,None,None,None
28,29,Plate,SA–738,B,K12007,None,None,1,3.0,585,...,None,None,None,None,None,None,None,None,None,None
29,30,Forgings,SA–372,C,K04801,None,None,None,NaN,620,...,None,None,None,None,None,None,None,None,None,None
30,31,Plate,SA–724,A,K11831,None,None,1,4.0,620,...,None,None,None,None,None,None,None,None,None,None
31,32,Plate,SA–724,C,K12037,None,None,1,4.0,620,...,None,None,None,None,None,None,None,None,None,None
32,33,Plate,SA–724,B,K12031,None,None,1,4.0,655,...,None,None,None,None,None,None,None,None,None,None
33,34,Plate,SA–737,B,K12001,None,None,1,2.0,485,...,None,None,None,None,None,None,None,None,None,None
36,37,Plate,SA/GB 713,Q370R,None,Normalized,64 < t ≤ 100,1,2.0,510,...,None,None,None,None,None,None,None,None,None,None
37,38,Plate,SA/GB 713,Q370R,None,Normalized,36 < t ≤ 60,1,2.0,520,...,None,None,None,None,None,None,None,None,None,None
38,39,Plate,SA/GB 713,Q370R,None,Normalized,16 < t ≤ 36,1,2.0,530,...,None,None,None,None,None,None,None,None,None,None
39,40,Plate,SA/GB 713,Q370R,None,Normalized,10 ≤ t ≤ 16,1,2.0,530,...,None,None,None,None,None,None,None,None,None,None
40,41,Plate,SA–737,C,K12202,None,None,1,3.0,550,...,None,None,None,None,None,None,None,None,None,None
41,42,Plate,SA–656,T3,None,None,≤50,1,1.0,414,...,None,None,None,None,None,None,None,None,None,None
42,43,Plate,SA–656,T7,None,None,≤50,1,1.0,414,...,None,None,None,None,None,None,None,None,None,None
43,44,Plate,SA–656,T3,None,None,≤40,1,2.0,483,...,None,None,None,None,None,None,None,None,None,None
44,45,Plate,SA–656,T7,None,None,≤40,1,2.0,483,...,None,None,None,None,None,None,None,None,None,None

In [38]:
mask = (dffin[10] > 310) & (dffin[10] < 330)
dffilter = dffin[mask]
filename = 'filter' + str(n) + '.csv'
dffilter.to_csv(filename)

In [39]:
dffilter

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
16,17,Plate,SA–299,B,K02803,None,≤25,1,3.0,550,...,None,None,None,None,None,None,None,None,None,None

In [31]:
dffin[10]

0     275.0
1     275.0
2     275.0
3     290.0
4     290.0
5     310.0
6     310.0
7     310.0
8     345.0
9     380.0
10    380.0
11    380.0
12    415.0
13    415.0
14    410.0
15    310.0
16    325.0
17    345.0
18    380.0
19    415.0
20    415.0
21    415.0
22    415.0
23    415.0
24    415.0
25    450.0
26    345.0
27    345.0
28    415.0
29    380.0
30    485.0
31    485.0
32    515.0
33    345.0
34      NaN
35      NaN
36    330.0
37    340.0
38    360.0
39    370.0
40    415.0
41    345.0
42    345.0
43    414.0
44    414.0
Name: 10, dtype: float64

In [18]:
filename = 'dictionary' + str(n) + '.txt'
f = open(filename, 'w')
for i in range(len(d)):
    f.write('\n')
    print('i = ', i, '-------------------', file = f)
    f.write(d[i])
f.close()